_PartialView/Models/Employee.cs
namespace DynamicPartialView.Models
{
    public class Employee
    {
        public int Age { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
    }
}

_PartialView/Models/ErrorViewModel.cs
namespace DynamicPartialView.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

_PartialView/Models/Intro.cs
namespace DynamicPartialView.Models
{
    public class Intro
    {
        public string Enterence { get; set; }
        public string Description { get; set; }
    }
}

_PartialView/Models/Phone.cs
namespace DynamicPartialView.Models
{
    public class Phone
    {
        public string PhoneNumber { get; set; }
        public string Owner { get; set; }
    }
}

_PartialView/Controllers/EmployeeController.cs
using DynamicPartialView.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace DynamicPartialView.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            return View(new Employee()
            {
                Age = 23,
                FirstName = "Khanim",
                LastName = "Gurbanli",
                Address = "Baku,Azerbaijan",
            });
        }
    }
}

_PartialView/Controllers/HomeController.cs
using DynamicPartialView.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DynamicPartialView.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            List<Intro> list = new List<Intro>
            {
                new Intro
            {
                Enterence = "Welcome Home",
                Description = "Here is for dynamic partial view page"
            },
                new Intro
            {
                Enterence = "Welcome Home list",
                Description = "Here is for dynamic partial view page list"
            }
           };

            return View(list);
        }
    }
}

_PartialView/Controllers/PhoneController.cs
using DynamicPartialView.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace DynamicPartialView.Controllers
{
    public class PhoneController : Controller
    {
        public IActionResult Index()
        {
            return View(new Phone()
            {
               PhoneNumber= "5034562923",
               Owner="Khanim Gurbanli"
            });
        }
    }
}

_PartialView/Views/Employee/Index.cshtml
@model Employee

@{
    Html.RenderPartial("_dynPartial", @Model);
}

_PartialView/Views/Home/Index.cshtml
@model IEnumerable<Intro>

@{
    Html.RenderPartial("_dynPartial", @Model);
}

_PartialView/Views/Phone/Index.cshtml
@model Phone

@{
    Html.RenderPartial("_dynPartial", @Model);
}

_PartialView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DynamicPartialView</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DynamicPartialView.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DynamicPartialView</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phone" asp-action="Index">Phone</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DynamicPartialView - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

_PartialView/Views/Shared/_dynPartial.cshtml
@model Object

@if (Model is IEnumerable<Object>)
{
    @foreach (var model in (IEnumerable<Object>)Model)
    {
        @foreach (var item in model.GetType().GetProperties())
        {
            <form>
                <label>@item.Name</label>
                <input class="form-control valid" type="text" value="@item.GetValue(model)" aria-invalid="false">
            </form>
        }
    }
}
else
{
    @foreach (var item in Model.GetType().GetProperties())
    {
        <form>
            <label>@item.Name</label>
            <input class="form-control valid" type="text" value="@item.GetValue(Model)" aria-invalid="false">
        </form>
    }
}